name: build
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:
env:
  GRADLE_OPTS: >-
    -Dorg.gradle.project.org.alfresco.maven.nexus.username=${{ secrets.ALFRESCO_NEXUS_USERNAME }}
    -Dorg.gradle.project.org.alfresco.maven.nexus.password=${{ secrets.ALFRESCO_NEXUS_PASSWORD }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: test -x :integration-tests:test
      - name: Upload Test Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: /home/runner/work/**/build/reports
          retention-days: 2
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Integration test
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: integration-tests:test
      - name: Upload Test Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-result
          path: /home/runner/work/**/build/reports
          retention-days: 2
  publish:
    needs: [ test, integration-test ]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Publish
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.SONATYPE_S01_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.SONATYPE_S01_PASSWORD }}
        with:
          cache-read-only: false
          arguments: publish -PsigningKeyId=CDE3528F -i
