name: build
on:
  push:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Test
        run: ./gradlew integration-tests:solr6:integrationTests

  publish:
    needs: [integration-tests]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/master') || startswith(github.ref, 'refs/heads/release') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatype_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_sonatype_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: ./gradlew publish -Psonatype_username=${ORG_GRADLE_PROJECT_sonatype_username} -Psonatype_password=${ORG_GRADLE_PROJECT_sonatype_password} -Psigning.keyId=${ORG_GRADLE_PROJECT_signingKey} -Psigning.password=${ORG_GRADLE_PROJECT_signingPassword}"
